// File generated by flutterfire_cli.
// DO NOT EDIT. This file is generated by the `flutterfire configure` command and should be regenerated
// whenever Firebase project settings change.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeUZszTjgAEjxtcRqjpClKxo-Ro7g_2Ls',
    appId: '1:13929643292:web:a4d993705e0e1fd8a4ced9',
    messagingSenderId: '13929643292',
    projectId: 'jeff-q17',
    authDomain: 'jeff-q17.firebaseapp.com',
    storageBucket: 'jeff-q17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDFWIQsqB2rLymsclzvyynpCe-FgpiyI',
    appId: '1:13929643292:android:7afd7b6e6a44ec64a4ced9',
    messagingSenderId: '13929643292',
    projectId: 'jeff-q17',
    storageBucket: 'jeff-q17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEFjpSqEEu0wReg4FF-975RD1S8I3Wrk',
    appId: '1:13929643292:ios:5261ce2647c2e515a4ced9',
    messagingSenderId: '13929643292',
    projectId: 'jeff-q17',
    storageBucket: 'jeff-q17.firebasestorage.app',
    iosClientId: '13929643292-4fh3cqga3lsd9hqi1nvstm1rdggpdeu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.p17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEFjpSqEEu0wReg4FF-975RD1S8I3Wrk',
    appId: '1:13929643292:ios:5261ce2647c2e515a4ced9',
    messagingSenderId: '13929643292',
    projectId: 'jeff-q17',
    storageBucket: 'jeff-q17.firebasestorage.app',
    iosClientId: '13929643292-4fh3cqga3lsd9hqi1nvstm1rdggpdeu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.p17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeUZszTjgAEjxtcRqjpClKxo-Ro7g_2Ls',
    appId: '1:13929643292:web:8db42694005f085ba4ced9',
    messagingSenderId: '13929643292',
    projectId: 'jeff-q17',
    authDomain: 'jeff-q17.firebaseapp.com',
    storageBucket: 'jeff-q17.firebasestorage.app',
  );

}